version: '2.1'
services:
  api:
    build: .
    container_name: "gis-api"
    links:
      - mongo
    ports:
      - "4000:4000"
  mongo:
    image: "mongo"
    container_name: "mongo-gis"
    ports:
      - "27017:27017"
networks:
  default:
    external:
      name: gis-networks
