version: '2.1'
services:
  api:
    build: .
    container_name: "gis-api"
    links:
      - mongo
    ports:
      - "4000:4000"
  mongo:
    image: "mongo"
    container_name: "mongo-gis"
    ports:
      - "27017:27017"

  # node-exporter:
  #   image: "prom/node-exporter"
  #   container_name : "node_exporter_gis"
  #   ports:
  #     - '9100:9100'
  #
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - ./prometheus_db:/var/lib/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   restart: unless-stopped
  #   links:
  #     - node-exporter
  #   ports:
  #     - '9090:9090'
  #
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=secure_pass
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - prometheus
  #   volumes:
  #     - ./grafana_db:/var/lib/grafana
  #   user: "1000"

networks:
  default:
    external:
      name: gis-networks
