global:
  scrape_interval: 5s
  external_labels:
    monitor: 'prakash-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'exporter'
    static_configs:
      - targets: ['node-exporter:9100'] ## IP Address of the localhost
